/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Gui.java
 *
 * Created on 20 nov. 2010, 10:24:36
 */

package gui;

/**
 *
 * @author Administrator
 */
public class Gui extends javax.swing.JFrame {

    /** Creates new form Gui */
    public Gui() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabbedPane = new javax.swing.JTabbedPane();
        movementsTab = new gui.ListingPanel();
        accountsTab = new gui.ListingPanel();
        budgetsTab = new gui.ListingPanel();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Account manager");
        getContentPane().setLayout(null);

        tabbedPane.addTab("Movements", movementsTab);
        tabbedPane.addTab("Accounts", accountsTab);
        tabbedPane.addTab("Budgets", budgetsTab);

        getContentPane().add(tabbedPane);
        tabbedPane.setBounds(0, 0, 400, 280);

        fileMenu.setText("File");
        menuBar.add(fileMenu);

        setJMenuBar(menuBar);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Gui().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private gui.ListingPanel accountsTab;
    private gui.ListingPanel budgetsTab;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenuBar menuBar;
    private gui.ListingPanel movementsTab;
    private javax.swing.JTabbedPane tabbedPane;
    // End of variables declaration//GEN-END:variables

}
