
/*
 * Gui.java
 *
 * Created on 15 déc. 2010, 07:07:03
 */
package gui;

import accountancy.accounts.Account;
import java.util.Iterator;
import java.util.Set;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import manager.Manager;

/**
 *
 * @author Matthieu Vergne <matthieu.vergne@gmail.com>
 */
public class Gui extends javax.swing.JFrame {

    private final Manager manager;

    /** Creates new form Gui */
    public Gui() {
        //TODO récupérer depuis la sauvegarde si présente
        manager = new Manager();

        initComponents();

        fillAccountsTable();
    }

    public void fillAccountsTable() {
        TableModel lastModel = accountsTable.getModel();

        Object[] columnNames = new Object[] { "Name", "Value", "Limit" };

        Set<Account> accounts = manager.getAccounts();
        Iterator<Account> iterator = accounts.iterator();
        Object[][] data = new Object[accounts.size()][columnNames.length];
        for(int i = 0 ; i < data.length ; i ++) {
                Account account = iterator.next();
                data[i][0] = account.getName();
                data[i][1] = account.getValue();
                data[i][2] = account.getLimit();
        }

        DefaultTableModel newModel =
                          new DefaultTableModel(data, columnNames);
        accountsTable.setModel(newModel);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabbedPane = new javax.swing.JTabbedPane();
        accountsPanel = new javax.swing.JPanel();
        accountsScrollPane = new javax.swing.JScrollPane();
        accountsTable = new javax.swing.JTable();
        budgetsPanel = new javax.swing.JPanel();
        movementsPanel = new javax.swing.JPanel();
        menuBar = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        accountsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        accountsScrollPane.setViewportView(accountsTable);

        javax.swing.GroupLayout accountsPanelLayout = new javax.swing.GroupLayout(accountsPanel);
        accountsPanel.setLayout(accountsPanelLayout);
        accountsPanelLayout.setHorizontalGroup(
            accountsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(accountsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(accountsScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 375, Short.MAX_VALUE)
                .addContainerGap())
        );
        accountsPanelLayout.setVerticalGroup(
            accountsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(accountsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(accountsScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 324, Short.MAX_VALUE)
                .addContainerGap())
        );

        tabbedPane.addTab("Accounts", accountsPanel);

        javax.swing.GroupLayout budgetsPanelLayout = new javax.swing.GroupLayout(budgetsPanel);
        budgetsPanel.setLayout(budgetsPanelLayout);
        budgetsPanelLayout.setHorizontalGroup(
            budgetsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 395, Short.MAX_VALUE)
        );
        budgetsPanelLayout.setVerticalGroup(
            budgetsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 346, Short.MAX_VALUE)
        );

        tabbedPane.addTab("Budgets", budgetsPanel);

        javax.swing.GroupLayout movementsPanelLayout = new javax.swing.GroupLayout(movementsPanel);
        movementsPanel.setLayout(movementsPanelLayout);
        movementsPanelLayout.setHorizontalGroup(
            movementsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 395, Short.MAX_VALUE)
            .addGap(0, 395, Short.MAX_VALUE)
        );
        movementsPanelLayout.setVerticalGroup(
            movementsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 346, Short.MAX_VALUE)
            .addGap(0, 346, Short.MAX_VALUE)
        );

        tabbedPane.addTab("Movements", movementsPanel);

        getContentPane().add(tabbedPane);

        jMenu1.setText("File");
        menuBar.add(jMenu1);

        jMenu2.setText("Edit");
        menuBar.add(jMenu2);

        setJMenuBar(menuBar);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Gui().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel accountsPanel;
    private javax.swing.JScrollPane accountsScrollPane;
    private javax.swing.JTable accountsTable;
    private javax.swing.JPanel budgetsPanel;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JPanel movementsPanel;
    private javax.swing.JTabbedPane tabbedPane;
    // End of variables declaration//GEN-END:variables
}
